### ISSUE TITLE
Deprecated dependency? 

### ISSUE THREAD

**Issue by rromerogar** [appfeel/analytics-google#10]
This plugins depends of com.google.play.services, but if you go to its web:

https://github.com/MobileChromeApps/google-play-services

It shows:

> THIS PLUGIN IS DEPRECATED!!! Plugins should use framework tags instead.
> 
> E.g.: <framework src="com.google.android.gms:play-services-plus:+" /> <framework >src="com.google.android.gms:play-services-identity:+" />
> 
> Full list available: http://developer.android.com/google/play-services/setup.html

**Comment by enricodeleo** [comment]
+1

**Comment by polyn0m** [comment]
This was fixed by #14
