### ISSUE TITLE
Setting custom dimensions?

### ISSUE THREAD

**Issue by shql** [appfeel/analytics-google#16]
Hello!

Forgive me if I don't see the obvious but I am struggling to set custom dimensions with this plugin just as I am used to with the official JavaScript SDK.

E.g.

`var dimensionValue = 'SOME_DIMENSION_VALUE';`
`ga('set', 'dimension1', dimensionValue);`

I tried to use the "setCustomParam" function but it does not work as expected. Also this would generate string values for the key if I am not mistaken. I'd like to have it exactly as Google puts it in its documentation:

**Android**
`String dimensionValue = "SOME_DIMENSION_VALUE";`
`tracker.set(Fields.customDimension(1), dimensionValue);`

**iOS**
`NSString *dimensionValue = @"SOME_DIMENSION_VALUE";`
`[tracker set:[GAIFields customDimensionForIndex:1] value:dimensionValue];`

Thank you very much for a hint!

**Comment by miqmago** [comment]
There are 3 ways:
- Set custom dimensions (multiple values):

``` js
analytics.setCustomParams({
  "&cn": "dec2014",
  "&cs": "http://appfeel.com"
});
```
- Set custom dimension `analytics.setCustomParam(key, value, success, error);`
- When the method is called:

``` javascript
    var options = {};

    options[analytics.OPTIONS.PRODUCT_ID] = "P12345";
    options[analytics.OPTIONS.PRODUCT_NAME] = "AppFeel Warhol T-Shirt";
    options[analytics.OPTIONS.PRODUCT_CATEGORY] = "Apparel/T-Shirts";
    options[analytics.OPTIONS.PRODUCT_BRAND] = "AppFeel";
    options[analytics.OPTIONS.PRODUCT_VARIANT] = "Black";
    options[analytics.OPTIONS.PRODUCT_POSITION] = 2;
    options[analytics.OPTIONS.PRODUCT_SCREEN_NAME] = "My Impression Screen";
    options[analytics.OPTIONS.PRODUCT_QUANTITY] = 2;
    options[analytics.OPTIONS.PRODUCT_PRICE] = 18.99;
    options[analytics.OPTIONS.PRODUCT_LIST] = "Search Results";
    options[analytics.OPTIONS.CUSTOM_DIMENSIONS] = {
      1: "Member"
    };
    options[analytics.OPTIONS.CUSTOM_METRICS] = {
      1: 30,
      4: 1.23
    };

    analytics.trackEcommerce(options);
```

Please see https://github.com/appfeel/analytics-google#setcustomparamsoptions-success-error and https://github.com/appfeel/analytics-google#measuring-impressions

**Comment by miqmago** [comment]
The last one is for dimensions, the other two are for custom parameters :)

**Comment by shql** [comment]
It works... of course. :-) Thank you very much. (Using it with `trackView` instead).
