### ISSUE TITLE
Build errors:

### ISSUE THREAD

**Issue by jvjvjv** [appfeel/analytics-google#19]
When running `cordova run ios` on my project I catch the following error during build

    /Project/platforms/ios/Pods/FirebaseCore/Firebase/Core/FIRLogger.m:18:9: fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h'
          file not found
    #import <GoogleUtilities/GULAppEnvironmentUtil.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

And when I just open the Xcode Workspace and try running the app I get the following error:

     Use of unresolved identifier 'FIRApp'

I've already run `pod install` and `pod update` and neither helped. Can't build or run the project with these errors. Can you help out?

**Comment by jvjvjv** [comment]
Note:

I had some build flags causing a problem in my build.json file. Specifically,

            "buildFlag": [
                "-UseModernBuildSystem=0",
                "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
                "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
                "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\""
            ]

were part of the build flags. I have narrowed it down to "-UseModernBuildSystem" which I had needed to build my project earlier. Right now the project seems to be building just fine, so I removed it and it looks like I am no longer seeing the issue. Of course, now I'm getting an Export error, but this is definitely on my side.

**Comment by miqmago** [comment]
Hmm that's quite strange.

Please could you output the version of cordova and `cordova-plugin-analytics` you are using?
```sh
cordova --version
cordova platform ls
cordova plugin ls
```
Also could you post the content of `platforms/ios/pods.json` and `platforms/ios/Podfile`?
```sh
cat platforms/ios/pods.json
cat platforms/ios/Podfile
ls -la platforms/ios/Pods
```

`Podfile` should be similar to:
```
# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '8.0'
target 'Quickstarter' do
        project 'Quickstarter.xcodeproj'
        pod 'FirebaseMessaging', '~> 2.0.0'
        pod 'FirebaseAnalytics', '>= 4.0.0'
end
```

**Comment by jvjvjv** [comment]
`$ cordova --version`

    8.1.2 (cordova-lib@8.1.1)

`$ cordova platforms list`

    Installed platforms:
      ios 4.5.5
    (etc)

`$ cordova plugins list`

    cordova-plugin-analytics 2.0.0 "Google Analytics Firebase Plugin"

`$ cat platforms/ios/pods.json`

    {
        "FirebaseAnalytics": {
            "name": "FirebaseAnalytics",
            "type": "podspec",
            "spec": ">= 4.0.0",
            "count": 1
        }
    }

`$ cat platforms/ios/Podfile`

    # DO NOT MODIFY -- auto-generated by Apache Cordova
    platform :ios, '8.0'
    target 'App' do
    	project 'App.xcodeproj'
        pod 'Firebase'
    end

`$ ls -la platforms/ios/Pods`

    total 8
    drwxr-xr-x  13 jason  staff   476 Jan 21 13:15 .
    drwxr-xr-x  13 jason  staff   748 Jan 21 15:27 ..
    drwxr-xr-x   3 jason  staff   238 Jan 21 13:15 Firebase
    drwxr-xr-x   3 jason  staff   102 Jan 21 13:15 FirebaseAnalytics
    drwxr-xr-x   3 jason  staff   170 Jan 21 13:15 FirebaseCore
    drwxr-xr-x   3 jason  staff   170 Jan 21 13:15 FirebaseInstanceID
    drwxr-xr-x   3 jason  staff   102 Jan 21 13:15 GoogleAppMeasurement
    drwxr-xr-x   3 jason  staff   170 Jan 21 13:15 GoogleUtilities
    drwxr-xr-x   4 jason  staff   136 Jan 21 13:15 Headers
    drwxr-xr-x   2 jason  staff    68 Jan 21 13:15 Local Podspecs
    -rw-r--r--   1 jason  staff  2512 Jan 21 13:15 Manifest.lock
    drwxr-xr-x@  3 jason  staff   136 Jan 21 13:17 Pods.xcodeproj
    drwxr-xr-x   6 jason  staff   204 Jan 21 13:15 Target Support Files
    drwxr-xr-x   2 jason  staff   374 Jan 21 13:15 nanopb

Just so you are aware, the original Podfile looked like what you have above. I could not get the error to go away until I changed the pod 'FirebaseAnalytics' to just 'Firebase.'

**Comment by miqmago** [comment]
So if I understood right, replacing FirebaseAnalytics by Firebase it works fine?

**Comment by etiennea** [comment]
This does not work!

**Comment by AndrWeisR** [comment]
How I fixed this:

1. Install the Firebase/Core and Firebase/Analytics pods:
Edit platforms/ios/Podfile, to install the Firebase/Analytics pod instead of FirebaseAnalytics, and add Firebase/Core:
```
# DO NOT MODIFY -- auto-generated by Apache Cordova
platform :ios, '9.0'
target 'App' do
    project 'App.xcodeproj'
    pod 'Firebase/Core'
    pod 'Firebase/Analytics'
end
```
In the same folder as the Podfile, run `pod install`.

2. Open the generated platforms/ios/App.xcworkspace

3. In Xcode, edit Plugins>CDVGoogleAnalytics.m to change `@import FirebaseAnalytics` to `@import Firebase`.
