### ISSUE TITLE
setDispatchPeriod on Android Not Working

### ISSUE THREAD

**Issue by awei-cp** [appfeel/analytics-google#2]
I was using setDispatchPeriod, but found that it does not work on Android.  The issue can be traced to the constant value "ACTION_SET_DISPATCH_PERIOD" in CPGoogleAnalytics.java.  The value should be "setDispatchPeriod", but it is currently "startDispatchPeriod"

Thanks for the plugin!

**Comment by appfeel** [comment]
Hi @awei-cp, sorry for the delay. Thanks for this issue, I've pushed and published it with a new version: 

https://github.com/appfeel/analytics-google/commit/31dfb8b29a5029b330f8008c5c21d291ca337542
