### ISSUE TITLE
iOS Build Error

### ISSUE THREAD

**Issue by SimonBrazell** [appfeel/analytics-google#22]
Hello I'm trying to move over to this plugin from the google-analytics-plugin now that the GA SDK for mobile apps is being [retired](https://support.google.com/analytics/answer/9167112?hl=en) but am having some grief. 

I can see there are related issues here on the repo but none of them seem to have a resolution and have been closed.

Running `ionic cordova build --release --prod ios -- --buildFlag="-UseModernBuildSystem=0"` results in the following error:

```
=== BUILD TARGET FirebaseCore OF PROJECT Pods WITH CONFIGURATION Release ===

...

fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
#import <GoogleUtilities/GULAppEnvironmentUtil.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

```
$ ionic info
Ionic:

   ionic (Ionic CLI)  : 4.10.1 (.../.nvm/versions/node/v8.14.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 3.1.1, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (.../Library/Android/sdk/)
   ios-deploy        : 1.9.4
   NodeJS            : v8.14.0 (.../.nvm/versions/node/v8.14.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61
```
```
$ ionic cordova plugin ls
> cordova plugin ls
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-annotated-plugin-android 1.0.4 "cordova-annotated-plugin-android"
cordova-play-services-version-adapter 1.0.2 "Cordova/Ionic Google Play Services Versions Incompatibility Adapter"
cordova-plugin-analytics 2.0.0 "Google Analytics Firebase Plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
screen shot 2019-01-31 at 3 19 23 pm
```

Trying to build the project in Xcode yields the following result:

![screen shot 2019-01-31 at 3 19 23 pm](https://user-images.githubusercontent.com/16571951/52104027-a0d94e80-263c-11e9-8b83-4acb8f8a4bda.png)

Please let me know if there is any more info I can give, cheers!

**Comment by sta55en** [comment]
https://stackoverflow.com/questions/37328508/ios-firebase-error-use-of-unresolved-identifier-firapp-running-supplied-code

**Comment by SimonBrazell** [comment]
Thanks @sta55en, I'll give this a try today.

One other thing I was curious about was adding the Google-services.json (android) and GoogleService-info.plist (ios) from Firebase console to your project. Do I have to drag them into the platform folders each time I build or will they stay there between builds? Is there a better way to do this?

Sorry for all the questions, but thank you very much for your help!

**Comment by SimonBrazell** [comment]
None of those solutions worked for me, those errors still remain despite running `pod install` / `pod update`, changing the Podfile as suggested, changing the code in `CDVGoogleAnalytics.m` replacing `FIRApp` with `FirebaseApp`, etc.

I think this plugin is broken on iOS, at least with the `-UseModernBuildSystem=0` build flag, which I need to build my project on iOS.

**Comment by vadimwe** [comment]
> None of those solutions worked for me, those errors still remain despite running `pod install` / `pod update`, changing the Podfile as suggested, changing the code in `CDVGoogleAnalytics.m` replacing `FIRApp` with `FirebaseApp`, etc.
> 
> I think this plugin is broken on iOS, at least with the `-UseModernBuildSystem=0` build flag, which I need to build my project on iOS.

**I confirm. No working solutions.**

**Comment by pdyxs** [comment]
Having the same problem building in XCode as well, has anyone made any progress on this?

**Comment by etiennea** [comment]
Yes this is not working

**Comment by unreal91** [comment]
@simonbrazell did you find any other way to build the app? Same issue here none of the solutions worked

**Comment by sta55en** [comment]
Instead of using this library, just use https://github.com/arnesson/cordova-plugin-firebase, it works like a charm.

**Comment by SimonBrazell** [comment]
@unreal91 no I gave up at that point, as the client was okay to wait for a fix, I might try `cordova-plugin-firebase` instead as @sta55en has suggested.

**Comment by aasif** [comment]
@simonbrazell did you find any solution to this? I am also trying to switch over to firebase analytics but facing conflicts with phonegap-push plugin. Would be great if I could get a lead on this.

**Comment by SimonBrazell** [comment]
@aasif no the client has not requested this feature again since I last investigated this, although I have some existing clients on the old platform that will need to be migrated soon so I'll be looking into this myself in the not too distant future. If I find a solution I'll be sure to post my findings here.

**Comment by aasif** [comment]
@simonbrazell do you recall which plugin was leading to this issue in your case?

**Comment by SimonBrazell** [comment]
@aasif I've since migrated to the [Firebase Analytics plugin](https://github.com/chemerisuk/cordova-plugin-firebase-analytics) which was quite simple and straight forward.
