### ISSUE TITLE
Currency not implemented in options

### ISSUE THREAD

**Issue by clarkbynum** [appfeel/analytics-google#5]
I tried passing in a "currencyCode" key to the options object but it doesn't look like it was passed in.
Here is my code for tracking eCommerce:

``` js
var options = {
  "category":"Ecommerce",
  "action":"Purchase",
  "productAction":"productActionPurchase",
  "transactionId":"211191",
  "transactionAffiliation":"DanCenter Mobile App",
  "transactionRevenue":373,
  "transactionTax":0,
  "transactionShipping":0,
  "currencyCode": "GBP"
};
  analytics.trackEcommerce(options, function() {
    console.log("successful trackEcommerce");
  }, function(err) {
    console.log('failed trackEcommerce ' + err);
  });
```

And here is the log in xCode:

2015-05-15 16:52:45.074 DanCenter[4269:1437094] VERBOSE: GoogleAnalytics 3.10 -[GAIBatchingDispatcher persist:](GAIBatchingDispatcher.m:497): Saved hit: {
    parameters =     {
        "&_crc" = 0;
        "&_u" = ".yL";
        "&_v" = "mi3.1.0";
        "&a" = 2070375777;
        "&aid" = "com.dancenter.renterapp";
        "&an" = DanCenter;
        "&av" = "0.0.1";
        "&cd" = Search;
        "&cid" = "b11a2160-9c0a-4188-bb21-04d9d53fb614";
        "&ds" = app;
        "&ea" = Purchase;
        "&ec" = Ecommerce;
        "&el" = "<null>";
        "&ev" = 0;
        "&sr" = 375x667;
        "&t" = event;
        "&ta" = "DanCenter Mobile App";
        "&ti" = 211191;
        "&tid" = "UA-62582311-1";
        "&tr" = 373;
        "&ts" = 0;
        "&tt" = 0;
        "&uid" = "my-user-id";
        "&ul" = en;
        "&v" = 1;
        "&z" = 11615818070055916929;
        gaiVersion = "3.10";
    };
    timestamp = "2015-05-15 21:52:45 +0000";
}

Am I missing something?

**Comment by miqmago** [comment]
https://github.com/appfeel/analytics-google#specifying-currency:

``` js
analytics.setCustomParam("&cu", "EUR");
```

Anyway this feature is now implemented with `currencyCode` parameter
