### ISSUE TITLE
trackEcommerce method does not work

### ISSUE THREAD

**Issue by clarkbynum** [appfeel/analytics-google#6]
Hi, I am trying to debug an issue with the trackEcommerce method. Everything seems to be set up correctly but I am not seeing any reports in my Analytics account (I have enabled ecommerce in the dashboard)

Here is my code (taken from the example project) -

```
 var options = {};
    options[analytics.OPTIONS.PRODUCT_ID] = "P12345";
    options[analytics.OPTIONS.PRODUCT_NAME] = "AppFeel Warhol T-Shirt";
    options[analytics.OPTIONS.PRODUCT_CATEGORY] = "Apparel/T-Shirts";
    options[analytics.OPTIONS.PRODUCT_BRAND] = "AppFeel";
    options[analytics.OPTIONS.PRODUCT_VARIANT] = "Black";
    options[analytics.OPTIONS.PRODUCT_POSITION] = 2;
    options[analytics.OPTIONS.PRODUCT_SCREEN_NAME] = "My Impression Screen";
    options[analytics.OPTIONS.PRODUCT_QUANTITY] = 2;
    options[analytics.OPTIONS.PRODUCT_PRICE] = 18.99;
    options[analytics.OPTIONS.PRODUCT_LIST] = "Related Products";
    options[analytics.OPTIONS.PRODUCT_LIST_SOURCE] = "My product list source";
    options[analytics.OPTIONS.PRODUCT_ACTION] = analytics.OPTIONS.PRODUCT_ACTION_DETAIL;
    options[analytics.OPTIONS.RELATED_PRODUCT_ID] = "P12346";
    options[analytics.OPTIONS.RELATED_PRODUCT_NAME] = "AppFeel Warhol T-Shirt";
    options[analytics.OPTIONS.RELATED_PRODUCT_CATEGORY] = "Apparel/T-Shirts";
    options[analytics.OPTIONS.RELATED_PRODUCT_BRAND] = "AppFeel";
    options[analytics.OPTIONS.RELATED_PRODUCT_VARIANT] = "White";
    options[analytics.OPTIONS.RELATED_PRODUCT_POSITION] = 2;
    options[analytics.OPTIONS.RELATED_PRODUCT_SCREEN_NAME] = "My Impression Screen";
    options[analytics.OPTIONS.RELATED_PRODUCT_QUANTITY] = 2;
    options[analytics.OPTIONS.RELATED_PRODUCT_PRICE] = 18.99;

    analytics.trackEcommerce(options, function() {console.log('successful trackEcommerce');}, function(err) {console.log('failed trackEcommerce ' + err);});
```

Here is the output in xCode:
      GoogleAnalytics 3.10 -[GAIBatchingDispatcher persist:](GAIBatchingDispatcher.m:497): Saved hit: {
       parameters =     {
        "&_crc" = 0;
        "&_u" = ".9KL";
        "&_v" = "mi3.1.0";
        "&a" = 1591618866;
        "&aid" = "com.dancenter.renterapp";
        "&an" = DanCenter;
        "&av" = "0.0.1";
        "&cd" = "My Impression Screen";
        "&cid" = "b11a2160-9c0a-4188-bb21-04d9d53fb614";
        "&ds" = app;
        "&il1ls" = "My product list source";
        "&il1nm" = "Related Products";
        "&il1pi1br" = AppFeel;
        "&il1pi1ca" = "Apparel/T-Shirts";
        "&il1pi1id" = P12346;
        "&il1pi1nm" = "AppFeel Warhol T-Shirt";
        "&il1pi1pr" = "18.99";
        "&il1pi1ps" = 2;
        "&il1pi1qt" = 2;
        "&il1pi1va" = White;
        "&pr1br" = AppFeel;
        "&pr1ca" = "Apparel/T-Shirts";
        "&pr1id" = P12345;
        "&pr1nm" = "AppFeel Warhol T-Shirt";
        "&pr1pr" = "18.99";
        "&pr1ps" = 2;
        "&pr1qt" = 2;
        "&pr1va" = Black;
        "&sr" = 375x667;
        "&t" = screenview;
        "&tid" = "UA-62582311-1";
        "&uid" = "my-user-id";
        "&ul" = en;
        "&v" = 1;
        "&z" = 17823308661167999488;
        gaiVersion = "3.10";
    };
    timestamp = "2015-05-18 18:02:16 +0000";
}

Please not that the success callback is fired as well. 

Is there something I'm missing?

**Comment by gihan9a** [comment]
@sh3nan1gans Did you able to resolve this? I'm having same issue

**Comment by miqmago** [comment]
Sorry for the late feedbak, it was resolved in an update but the issue wasn't closed. Please reopen again if still happens.
